- name: Clone Repo
  git:
    repo: "{{ repository }}"
    dest: "/home/{{ ansible_user }}/{{ app }}"
    version: "{{branch}}"
    force: yes
    accept_hostkey: yes
    key_file: "/home/{{ ansible_user }}/.ssh/cgus-bot-key"
  tags:
    - setup
    - update

- debug:
    msg: "Deploying '{{repository}}' for branch '{{branch}}' (commit '{{commit_sha}}') in folder '{{app}}' on port '{{app_port}}' and base path '{{base_path}}'"

- name: Build the image
  become: yes
  community.general.docker_image:
    source: build
    build:
      args:
        COMMIT: "{{ commit_sha }}"
      path: "/home/{{ ansible_user }}/{{ app }}"
    name: "{{ app }}"
    force_source: yes

- name: Start the container
  become: yes
  community.general.docker_container:
    name: "{{ app }}"
    image: "{{ app }}"
    restart: yes
    env:
      BASE_PATH: "{{ base_path }}"
    ports:
      - "{{ app_port }}:80"
