- name: Clone Repo
  git:
    repo: "{{ repository }}"
    dest: "/home/{{ ansible_user }}/{{ app }}"
    force: yes
    accept_hostkey: yes
    key_file: "/home/{{ ansible_user }}/.ssh/cgus-bot-key"
  tags:
    - setup
    - update

- name: Build the image
  become: yes
  community.general.docker_image:
    build:
      path: "/home/{{ ansible_user }}/{{ app }}"
    name: "{{ app }}"

- name: Start the container
  become: yes
  community.general.docker_container:
    name: "{{ app }}"
    image: "{{ app }}"
    restart: yes
    ports:
    - "{{ app_port }}:80"
    env:
      CGUS_API_ENV: "production"
