---
- name: Install docker dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip
    - python3-setuptools
    - python3

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/debian buster stable
    state: present

- name: install docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install docker with pip
  pip:
    name: docker

- name: Install docker-compose with pip
  pip:
    name: docker-compose

- name: Assure that docker is started
  service:
    name: docker
    state: started
    enabled: yes
